# FLEET CONFIG =================================================================
# RMF Fleet parameters

rmf_fleet:
  name: "leovac"
  fleet_manager:
    prefix: "api.lionsbot.io"  # host name
    user: ""
    password: ""
  limits:
    linear: [0.4, 0.2] # velocity, acceleration
    angular: [0.3, 0.35] # velocity, acceleration
  profile: # Robot profile is modelled as a circle
    footprint: 0.5 # radius in m
    vicinity: 0.6 # radius in m
  reversible: False # whether robots in this fleet can reverse
  battery_system:
    voltage: 24.0 # V
    capacity: 40.0 # Ahr
    charging_current: 26.4 # A
  mechanical_system:
    mass: 80.0 # kg
    moment_of_inertia: 20.0 #kgm^2
    friction_coefficient: 0.20
  ambient_system:
    power: 20.0 # W
  tool_system:
    power: 0.0 # W
  recharge_threshold: 0.10 # Battery level below which robots in this fleet will not operate
  recharge_soc: 0.45 # Battery level to which robots in this fleet should be charged up to during recharging tasks
  publish_fleet_state: True
  account_for_battery_drain: True
  task_capabilities: # Specify the types of RMF Tasks that robots in this fleet are capable of performing
    loop: True
    delivery: False
    clean: True
    custom_tasks: ["clean", manual]
    finishing_request: "nothing" # [park, charge, nothing]

robots:
  # Here the user is expected to append the configuration for each robot in the
  # fleet.
  # Configuration for first robot in this fleet
  leovac_01:  # robot identity name
    robot_config:
      robot_id: "LB03462"
      max_delay: 10.0 # allowed seconds of delay of the current itinerary before it gets interrupted and replanned
      dock_home_position: [1433, 2208, 0.0]  # robot start-up dock point coordinates
      dock_home_name: "dock_office"  # robot start-up dock point name
      clean_percentage_threshold: 0
    rmf_config:
      robot_state_update_frequency: 2
      max_merge_lane_distance: 15.0 # means how far will the robot diverge from the defined graph
      start:
        building_name: "RMF_test"
        map_name: "L2"
        # waypoint: "leovac_dock_1"  # robot start-up waypoint name
        # orientation: 3.13487579452652  # robot start-up dock point orientation
      charger:
        waypoint: "dock_office"
  leovac_02:  # robot identity name
    robot_config:
      robot_id: "LB03463"
      max_delay: 10.0 # allowed seconds of delay of the current itinerary before it gets interrupted and replanned
      dock_home_position: [1201, 1585, -1.56]  # robot start-up dock point coordinates
      dock_home_name: "dock_ps"  # robot start-up dock point name
      clean_percentage_threshold: 20
    rmf_config:
      robot_state_update_frequency: 2
      max_merge_lane_distance: 15.0 # means how far will the robot diverge from the defined graph
      start:
        building_name: "RMF_test"
        map_name: "L2"
        # waypoint: "dock_ps"  # robot start-up waypoint name
        # orientation: 3.13487579452652  # robot start-up dock point orientation
      charger:
        waypoint: "dock_ps"

reference_coordinates:
  L2:  # map transformation
    robot:
      - [1521, 2102]  # czone_a2_start
      - [1533, 1221]  # czone_a6_start
      - [4348, 1148]  # czone_b5_start
      - [4368, 2081]  # czone_b7_end
    rmf:
      - [355.2321, -109.4006]  # czone_a2_start
      - [354.4324, -153.5447]  # czone_a6_start
      - [213.0433, -156.4237]  # czone_b5_start
      - [212.2436, -109.5605]  # czone_b7_end
