from enum import Enum
from enum import IntEnum

class RobotStatus(Enum):
    CLEANING = "Cleaning"
    CLEANING_PAUSED = "Cleaning Paused"
    RESTING = "Resting"
    DOCKED = "Docked"
    MOVING = "Moving"
    MOVING_PAUSED = "Moving Paused"

class RobotMissionStatus(Enum):
   CLEANING = "ROBOT_CLEANING"
   CLEANING_FINISHED = 'ROBOT_CLEANING_FINISHED'
   MOVING = "ROBOT_MOVING"
   MOVING_FINISHED = 'ROBOT_MOVING_FINISHED'
   APP_STOPPED = 'APP_STOPPED'
   MOVING_STOPPED = 'ROBOT_MOVING_STOPPED'
   MOBVING_FINISHED = 'ROBOT_MOVING_FINISHED'
   E_STOP_PRESSED = 'USER_E_STOP_PRESSED'
   IN_CRITICAL = 'ROBOT_IN_CRITICAL'
   DOCKED = 'ROBOT_DOCKED'
   APP_MOVING_TO_DOCK_STOPPED = 'APP_MOVING_TO_DOCK_STOPPED'
   APP_DOCKING_STOPPED = 'APP_DOCKING_STOPPED'
   DOCKING_STOPPED = 'ROBOT_DOCKING_STOPPED'
   APP_MOVING_TO_WORK_STOPPED = 'APP_MOVING_TO_WORK_STOPPED'
   MOVING_TO_WORK_STOPPED = 'ROBOT_MOVING_TO_WORK_STOPPED'
   APP_CLEANING_STOPPED = 'APP_CLEANING_STOPPED'
   CLEANING_STOPPED = 'ROBOT_CLEANING_STOPPED'

class ActiveMissionType(Enum):
   IDLE = "IDLE"
   WORKING = "WORKING"
   MOVING = "MOVING"

class Topic(Enum):
    RMF_LITTER = "rmf_litter"
    LB_TASKS_REQUEST = "lb_task_api_requests"
    DOCK_SUMMARY = "dock_summary"

class ResponseCode(IntEnum):
  # Success
  P2P_STARTED = 4101

  # Error
  UNABLE_TO_PLAN_PATH = 3101
  DESTINATION_TOO_NEAR = 3102

class NavigationStatus: 
   NAVIGATION_SUCCESS = 'NAVIGATION_SUCCESS'
   NAVIGATION_ERROR = 'NAVIGATION_ERROR'
   NAVIGATING = 'NAVIGATING'
   EMPTY = 'EMPTY'
